flowchart TB
   3Abdallah --> Mohamed
   amina(Amîna Bint Wahb) --> Mohamed
   amina(Amîna Bint Wahb) --- 3Abdallah

   muttalib(3Abdul Al Muttalib) --> 3Abdallah
   fatima(Fâtima Bint 3Amru Al Makhzumiyya) --> 3Abdallah
   muttalib(3Abdul Al Muttalib) --- fatima(Fâtima Bint 3Amru Al Makhzumiyya)

   hachim(Hâchim) --> muttalib(3Abdul Al Muttalib)
   selma(Selma Bint 3Amrû An-najâriyya) --> muttalib(3Abdul Al Muttalib)
   hachim(Hâchim) --- selma(Selma Bint 3Amrû An-najâriyya)

   manaf(Manâf) --> hachim(Hâchim)
   atika(3Atika Bint Murra As-Sulmiyya) --> hachim(Hâchim)
   manaf(Manâf) --- atika(3Atika Bint Murra As-Sulmiyya)
