gantt
    title Histoire des califs
    dateFormat x
    axisFormat %L

    section Califs
        Abu Bakr               :a1, 11, 13
        Omar Ibn Al Khattab    :a2, after a1, 23
        Othman Ibn Affane      :a3, after a2, 35
        Ali Ibn Abi Tâlib      :a4, after a3, 40
