gantt
    title Histoire des imams
    dateFormat x
    axisFormat %L

    section Grands Imams
        Abu Hanifa                      :active, i1, 80, 150
        Malik Ibnou Anas                :active, i2, 93, 179
        Muhammad Ibn Idriss As-shafi3i  :active, i3, 150, 204
        Ahmed Ibn Hanbal                :active, i4, 164, 241
